### ISSUE TITLE
IsUnavailable:false UnavailableType: DecryptFailMode:}

### ISSUE THREAD

**Issue by xyzsoluciones** [asternic/wuzapi#134]
Is there an issue where Wuzapi stops working and requires a server restart? Messages are lost when you restart Wuzapi. Is this a bug or normal behavior?
IsUnavailable:false UnavailableType: DecryptFailMode:}

 WARN Unhandled event event="&{Info:{MessageSource:{Chat:xxxxx@s.whatsapp.net Sender:xxxx1@s.whatsapp.net IsFromMe:false IsGroup:false AddressingMode: SenderAlt:187746106736656@lid RecipientAlt: BroadcastListOwner:} ID:AC57002B39B7CE24105E79E6C92B4B04 ServerID:0 Type:text PushName:Fernando Timestamp:2025-09-25 20:30:51 -0500 -05 Category: Multicast:false MediaType: Edit: MsgBotInfo:{EditType: EditTargetID: EditSenderTimestampMS:0001-01-01 00:00:00 +0000 UTC} MsgMetaInfo:{TargetID: TargetSender: TargetChat: DeprecatedLIDSession:<nil> ThreadMessageID: ThreadMessageSenderJID:} VerifiedName:<nil> DeviceSentMeta:<nil>} IsUnavailable:false UnavailableType: DecryptFailMode:}"

**Comment by valneimelo** [comment]
I'm facing the same issue. I've noticed that the issue only occurs with messages from Instagram Ads. Could you please help us @asternic ? How to get it solved?

Thanks in advance

**Comment by valneimelo** [comment]
UPDATE: It seems it was fixed today, according to the commit: https://github.com/tulir/whatsmeow/commit/95e557a3b5289dae24dfe23088a777e4a050266d

Let's wait asternic release a new commit with the update for this issue.

**Comment by caiovsbraz** [comment]
It's happening to me. I just updated... But it's still happening.
