### ISSUE TITLE
Unable to obtain QR code or manage session status – endpoints return inconsistent responses

### ISSUE THREAD

**Issue by DiazAdriel0** [asternic/wuzapi#81]
Hi,

I'm having issues managing the session with WuzAPI. Specifically, I can't retrieve the QR code to start a session, and the various session-related endpoints return inconsistent or contradictory responses.

Here's a summary of the endpoints and their responses:

POST /session/connect → returns: "already connected"

POST /session/disconnect → returns: "Cannot disconnect because it is not logged in"

POST /session/logout → returns: "Could not disconnect as it was not connected"

GET /session/status → returns: {    "Connected": false,    "LoggedIn": false  }

GET /session/qr → returns: "Not connected"

GET /login/?token=mytoken → just shows a blank screen with the message "Welcome to Wuzapi"

It seems like I'm stuck in a state where I can't connect, disconnect, or retrieve the QR code.

I'll attach screenshots showing each response to help clarify.

Let me know if there's something I’m missing or if you need more info.
Thanks in advance!

Best regards,
Adriel

![Image](https://github.com/user-attachments/assets/30604dce-d08a-4800-b14c-24f069fb7675)

![Image](https://github.com/user-attachments/assets/94ebf9d6-1033-42e2-8945-7deab26d65b0)

![Image](https://github.com/user-attachments/assets/bf61cf3c-1e0c-49e4-90aa-8d94f44aaeb2)

![Image](https://github.com/user-attachments/assets/98e98e5b-f5ff-4b43-998a-bae4c7aab32e)

![Image](https://github.com/user-attachments/assets/c5ca0f4c-4596-405e-afd8-fc5fba753616)

![Image](https://github.com/user-attachments/assets/72a4f317-d1e5-480a-abd9-7fe0101332ba)

**Comment by asternic** [comment]
/login seams to be cached on your browser, or perhaps not updated, should look a bit different. Be sure to clear your browser cache or try incognito mode. Or you can try the new /dashboard endpoint

Regarding inconsistent status, try restarting wuzapi and try again after that.

**Comment by DiazAdriel0** [comment]
Thanks for the quick reply!

I already tried clearing my browser cache and also tested in incognito mode — the issue persists in both cases.
I also restarted the Docker container where I’m running WuzAPI, but the problem continues.

What I'll do next is pull the latest version, restart the Docker container again, and test everything from scratch.
I'll update this issue once I have the results.

**Comment by DiazAdriel0** [comment]
Thanks for the response. The issue was resolved by updating the code to the latest version and redeploying.

**Comment by cypwnpwnsocute** [comment]
Hello, I am using the latest version of the code to compile and deploy using docker, and I still have this problem.

![Image](https://github.com/user-attachments/assets/c92dffad-d0a5-4e2b-93e6-bf971f6ee174)
At the same time, I tested using a regular browser and privacy mode and still couldn't solve the problem
